const G={
alfabe:{theme:'Harf Bilgisi',icon:'🚂',title:'Alfabe Treni',badge:'Alfabe Makinisti Rozeti',q:[['Türk alfabesinde kaç harf vardır?','A B C ... Z',29,[29,28,30,26]],['Alfabede A’dan sonra hangi harf gelir?','A → ?', 'B',['B','C','Ç','D']],['Hangisi alfabede daha önce gelir?','K ? M','K',['K','M','N','L']],['P harfinden sonra hangisi gelir?','P → ?','R',['R','S','Ö','O']],['Hangi sıra doğrudur?','?','G – Ğ – H',['G – Ğ – H','Ğ – G – H','H – G – Ğ','G – H – Ğ']]]},
unlu:{theme:'Harf Bilgisi',icon:'🎤',title:'Sesli Harf Sahnesi',badge:'Ses Avcısı Rozeti',q:[['Hangisi ünlü harftir?','A E I İ O Ö U Ü','Ö',['Ö','K','M','Ş']],['“kalem” kelimesindeki ünlüler hangileridir?','k a l e m','a ve e',['a ve e','k ve l','l ve m','a ve m']],['Hangisi yalnız ünsüzlerden oluşur?','?','k, l, m',['k, l, m','a, e, ı','o, r, u','i, s, e']],['“üzüm” kelimesinde kaç ünlü vardır?','ü z ü m',2,[2,1,3,4]],['Türkçede kaç ünlü harf vardır?','A E I İ O Ö U Ü',8,[8,7,9,21]]]},
harfsayisi:{theme:'Harf Bilgisi',icon:'🔢',title:'Harf Sayacı',badge:'Harf Sayma Rozeti',q:[['“okul” kaç harflidir?','o-k-u-l',4,[4,3,5,2]],['“kitaplık” kaç harflidir?','k-i-t-a-p-l-ı-k',8,[8,7,6,9]],['Hangisi 5 harflidir?','?','kalem',['kalem','ev','masa','çocuklar']],['“öğretmen” kaç harflidir?','ö-ğ-r-e-t-m-e-n',8,[8,7,9,6]],['“arı” ile “bal” toplam kaç harftir?','arı + bal',6,[6,5,7,8]]]},
hecesayisi:{theme:'Hece Bilgisi',icon:'👏',title:'Hece Alkışı',badge:'Ritim Ustası Rozeti',q:[['“kalem” kaç hecelidir?','ka-lem',2,[2,1,3,4]],['“kelebek” kaç hecelidir?','ke-le-bek',3,[3,2,4,1]],['Hangisi tek hecelidir?','?','gül',['gül','masa','araba','kelebek']],['“öğretmen” kaç hecelidir?','öğ-ret-men',3,[3,2,4,5]],['“bilgisayar” kaç hecelidir?','bil-gi-sa-yar',4,[4,3,5,2]]]},
heceayir:{theme:'Hece Bilgisi',icon:'✂️',title:'Hece Makası',badge:'Hece Ustası Rozeti',q:[['“kitap” doğru nasıl ayrılır?','📘','ki-tap',['ki-tap','kit-ap','k-itap','ki-ta-p']],['“araba” doğru nasıl ayrılır?','🚗','a-ra-ba',['a-ra-ba','ar-ab-a','ara-ba','a-raba']],['“Türkiye” doğru nasıl ayrılır?','🇹🇷','Tür-ki-ye',['Tür-ki-ye','Türk-iye','Tür-kiye','Tü-rki-ye']],['“portakal” doğru nasıl ayrılır?','🍊','por-ta-kal',['por-ta-kal','port-a-kal','po-rta-kal','por-tak-al']],['“oyuncak” doğru nasıl ayrılır?','🧸','o-yun-cak',['o-yun-cak','oy-un-cak','o-yuncak','oyun-cak']]]},
heceden:{theme:'Kelime Bilgisi 1',icon:'🧱',title:'Hece Yapı Ustası',badge:'Kelime Kurucu Rozeti',q:[['“ki” ve “tap” hecelerinden hangi kelime oluşur?','ki + tap','kitap',['kitap','katip','kapı','takip']],['“o” + “yun” + “cak” hecelerini birleştir.','o | yun | cak','oyuncak',['oyuncak','oyuncu','ocak','uyacak']],['“ba” + “lık” hangi kelimeyi oluşturur?','ba + lık','balık',['balık','bakır','bilek','bal']],['“ke” + “le” + “bek” hecelerini birleştir.','ke | le | bek','kelebek',['kelebek','kepek','bebek','elek']],['“ar” + “ka” + “daş” hangi kelimedir?','ar | ka | daş','arkadaş',['arkadaş','kardeş','arkada','taş']]]},
cagrisim:{theme:'Kelime Bilgisi 1',icon:'💭',title:'Çağrışım Bulutu',badge:'Fikir Bulutu Rozeti',q:[['“deniz” kelimesi hangisini çağrıştırır?','🌊','dalga',['dalga','soba','kalem','dolap']],['“okul” denince hangisi akla gelir?','🏫','öğretmen',['öğretmen','gemi','orman','fırın']],['“kış” kelimesi hangisini çağrıştırır?','❄️','kar',['kar','plaj','kiraz','güneş kremi']],['“hastane” ile ilgili kelime hangisidir?','🏥','doktor',['doktor','pilot','manav','terzi']],['“doğum günü” hangisini çağrıştırır?','🎂','pasta',['pasta','trafik','çekiç','tarla']]]},
harita:{theme:'Kelime Bilgisi 1',icon:'🕸️',title:'Kelime Haritası',badge:'Bağlantı Ustası Rozeti',q:[['Merkezde “meyve” varsa hangisi haritaya eklenir?','meyve → ?','elma',['elma','sandalye','kalem','çorap']],['“taşıt” kelime haritasına hangisi uymaz?','🚗 🚌 🚲 ?','masa',['masa','araba','otobüs','bisiklet']],['“hayvan” merkezine hangi dal uygundur?','hayvan → ?','kedi',['kedi','kitap','ekmek','bardak']],['“duygular” haritasına hangisi eklenir?','❤️','sevinç',['sevinç','cetvel','çanta','kapı']],['“meslekler” haritasında hangisi bulunur?','👩‍🏫','öğretmen',['öğretmen','portakal','pencere','deniz']]]},
gorselanlat:{theme:'Kelime Bilgisi 1',icon:'🖼️',title:'Görsel Dedektifi',badge:'Görsel Okur Rozeti',q:[['Bu görsel ne anlatıyor?','🌧️☂️','Yağmur yağıyor.',['Yağmur yağıyor.','Güneş parlıyor.','Çocuk uyuyor.','Kar yağıyor.']],['Bu görselde ne oluyor?','👧📖','Çocuk kitap okuyor.',['Çocuk kitap okuyor.','Çocuk koşuyor.','Çocuk yemek yiyor.','Çocuk yüzüyor.']],['Görselin anlattığı duygu hangisidir?','😢','Üzüntü',['Üzüntü','Sevinç','Şaşkınlık','Öfke']],['Bu işaret ne anlatır?','🚭','Sigara içilmez.',['Sigara içilmez.','Koşmak serbesttir.','Yemek yenir.','Telefon açılır.']],['Görsele uygun cümle hangisidir?','🐦🌳','Kuş ağacın üzerindedir.',['Kuş ağacın üzerindedir.','Balık denizdedir.','Kedi uyuyor.','Çiçek soldu.']]]},
kelimegorsel:{theme:'Kelime Bilgisi 1',icon:'🔗',title:'Kelime–Görsel Köprüsü',badge:'Eşleştirme Rozeti',q:[['“şemsiye” kelimesinin görseli hangisidir?','şemsiye','☂️',['☂️','🧤','🧢','👟']],['🍓 görselinin adı nedir?','🍓','çilek',['çilek','kiraz','elma','üzüm']],['“kaplumbağa” hangisidir?','?','🐢',['🐢','🐇','🐈','🐝']],['🚲 görseli hangi kelimeyle eşleşir?','🚲','bisiklet',['bisiklet','otobüs','tren','gemi']],['“gökkuşağı” görselini seç.','?','🌈',['🌈','🌧️','☀️','❄️']]]},
anlam:{theme:'Kelime Bilgisi 1',icon:'🔎',title:'Anlam Hazinesi',badge:'Sözlük Kâşifi Rozeti',q:[['“cesur” kelimesinin anlamı hangisidir?','cesur','Korkmadan davranan',['Korkmadan davranan','Çok yavaş olan','Sürekli uyuyan','Kolay kırılan']],['“misafir” kimdir?','misafir','Bir yere konuk olarak gelen kişi',['Bir yere konuk olarak gelen kişi','Ev sahibi','Öğretmen','Sürücü']],['“özenli” ne demektir?','özenli','Dikkatli ve titiz',['Dikkatli ve titiz','Dağınık','Gürültülü','Karanlık']],['“anı” kelimesinin anlamı hangisidir?','anı','Geçmişte yaşanan olayın hatırası',['Geçmişte yaşanan olayın hatırası','Gelecek planı','Bir eşya','Bir yemek']],['“yolculuk” ne demektir?','🧳','Bir yerden başka yere gitme',['Bir yerden başka yere gitme','Evde uyuma','Resim çizme','Bahçe sulama']]]},
dogruyazim:{theme:'Kelime Bilgisi 2',icon:'🧹',title:'Yazım Tamircisi',badge:'Doğru Yazım Rozeti',q:[['Hangisi doğru yazılmıştır?','?','herkes',['herkes','herkez','her kes','herkesz']],['Doğru yazımı seç.','?','yalnız',['yalnız','yanlız','yalnış','yalınız']],['Hangisi doğrudur?','?','bir şey',['bir şey','birşey','bişey','bir sey']],['Doğru yazılan kelime hangisidir?','?','kirpik',['kirpik','kiprik','kirpikğ','kirbik']],['Hangisi doğru yazılmıştır?','?','şoför',['şoför','şöför','şöförü','şofor']]]},
anlamli:{theme:'Kelime Bilgisi 2',icon:'⚖️',title:'Anlam Terazisi',badge:'Anlam Seçici Rozeti',q:[['Hangisi tek başına anlamlıdır?','?','kitap',['kitap','ve','ile','ama']],['Hangisi tek başına anlamı olmayan kelimedir?','?','fakat',['fakat','çiçek','masa','çocuk']],['“Ali ile Ece geldi.” cümlesinde tek başına anlamı olmayan kelime hangisidir?','Ali ile Ece geldi.','ile',['ile','Ali','Ece','geldi']],['Hangisi tek başına anlamlıdır?','?','koşmak',['koşmak','veya','çünkü','ise']],['“ama” kelimesi için hangisi doğrudur?','ama','Cümlede bağlantı kurar.',['Cümlede bağlantı kurar.','Bir varlığın adıdır.','Bir eylemdir.','Bir renktir.']]]},
alfabetik:{theme:'Kelime Bilgisi 2',icon:'📚',title:'Sözlük Yarışı',badge:'Sıralama Şampiyonu Rozeti',q:[['Hangi sıralama alfabetiktir?','?','armut – elma – muz',['armut – elma – muz','muz – elma – armut','elma – armut – muz','armut – muz – elma']],['“balık, bebek, böcek” kelimelerinde önce hangisi gelir?','B...','balık',['balık','bebek','böcek','hepsi aynı']],['“kale” ve “kalem”den hangisi önce gelir?','kale / kalem','kale',['kale','kalem','ikisi aynı','belirsiz']],['Alfabetik sırada en sonra hangisi gelir?','araba, çanta, okul','okul',['okul','çanta','araba','hepsi']],['Doğru sıra hangisidir?','?','gemi – güneş – kitap',['gemi – güneş – kitap','kitap – güneş – gemi','güneş – gemi – kitap','gemi – kitap – güneş']]]},
satirsonu:{theme:'Kelime Bilgisi 2',icon:'📏',title:'Satır Sonu Köprüsü',badge:'Satır Ustası Rozeti',q:[['“kitaplık” satır sonunda nasıl bölünebilir?','kitap-\nlık','kitap- / lık',['kitap- / lık','kita- / plık','kitapl- / ık','ki- / taplık']],['Satır sonunda ayrılan kelimenin sonuna ne konur?','kelime ?','Kısa çizgi',['Kısa çizgi','Nokta','Virgül','Kesme işareti']],['“arkadaş” için uygun ayırma hangisidir?','?','ar- / kadaş',['ar- / kadaş','ark- / adaş','arkad- / aş','a- / rkadaş']],['Tek heceli “gül” satır sonunda nasıl davranır?','gül','Bölünmez.',['Bölünmez.','g- / ül olur.','gü- / l olur.','Her yerden ayrılır.']],['“öğretmen” için doğru satır sonu ayrımı hangisidir?','?','öğret- / men',['öğret- / men','öğre- / tmen','öğretm- / en','ö- / ğretmen']]]}
};
